import type {
  Employee,
  Mission,
  EmployeeAvailability,
  MessageThread,
  AppNotification,
} from "@/types";

const AVATAR_COLORS = [
  "#002F5C",
  "#005DAA",
  "#83700d",
  "#d7ba1d",
  "#1a7ec9",
  "#7a5d10",
  "#1c4684",
  "#b29714",
];

const initials = (first: string, last: string) =>
  `${first[0] ?? ""}${last[0] ?? ""}`.toUpperCase();

export const EMPLOYEES: Employee[] = [
  {
    id: "emp-1",
    firstName: "Sander",
    lastName: "de Vries",
    initials: initials("Sander", "de Vries"),
    email: "sander.devries@werkkompas.nl",
    phone: "+31 6 1234 5601",
    city: "Rotterdam",
    status: "actief",
    certifications: ["Beveiliger 2", "Evenementenbeveiliger", "BHV"],
    contractHoursPerWeek: 40,
    caoMaxHoursPerWeek: 48,
    hireDate: "2022-04-11",
    rating: 4.7,
    avatarColor: AVATAR_COLORS[0],
  },
  {
    id: "emp-2",
    firstName: "Fatima",
    lastName: "El Amrani",
    initials: initials("Fatima", "El Amrani"),
    email: "fatima.elamrani@werkkompas.nl",
    phone: "+31 6 1234 5602",
    city: "Den Haag",
    status: "actief",
    certifications: ["Beveiliger 2", "EHBO", "Centralist"],
    contractHoursPerWeek: 32,
    caoMaxHoursPerWeek: 48,
    hireDate: "2021-09-02",
    rating: 4.9,
    avatarColor: AVATAR_COLORS[1],
  },
  {
    id: "emp-3",
    firstName: "Jeroen",
    lastName: "Bakker",
    initials: initials("Jeroen", "Bakker"),
    email: "jeroen.bakker@werkkompas.nl",
    phone: "+31 6 1234 5603",
    city: "Amsterdam",
    status: "actief",
    certifications: ["Beveiliger 2", "Horeca Portier", "BHV"],
    contractHoursPerWeek: 40,
    caoMaxHoursPerWeek: 48,
    hireDate: "2020-01-15",
    rating: 4.5,
    avatarColor: AVATAR_COLORS[2],
  },
  {
    id: "emp-4",
    firstName: "Mila",
    lastName: "Janssen",
    initials: initials("Mila", "Janssen"),
    email: "mila.janssen@werkkompas.nl",
    phone: "+31 6 1234 5604",
    city: "Utrecht",
    status: "actief",
    certifications: ["Beveiliger 2", "Evenementenbeveiliger", "EHBO"],
    contractHoursPerWeek: 24,
    caoMaxHoursPerWeek: 48,
    hireDate: "2023-03-20",
    rating: 4.8,
    avatarColor: AVATAR_COLORS[3],
  },
  {
    id: "emp-5",
    firstName: "Youssef",
    lastName: "Hassan",
    initials: initials("Youssef", "Hassan"),
    email: "youssef.hassan@werkkompas.nl",
    phone: "+31 6 1234 5605",
    city: "Rotterdam",
    status: "actief",
    certifications: ["Beveiliger 2", "Persoonsbeveiliger", "BHV", "EHBO"],
    contractHoursPerWeek: 40,
    caoMaxHoursPerWeek: 48,
    hireDate: "2019-06-04",
    rating: 4.9,
    avatarColor: AVATAR_COLORS[4],
  },
  {
    id: "emp-6",
    firstName: "Lotte",
    lastName: "van Dijk",
    initials: initials("Lotte", "van Dijk"),
    email: "lotte.vandijk@werkkompas.nl",
    phone: "+31 6 1234 5606",
    city: "Eindhoven",
    status: "verlof",
    certifications: ["Beveiliger 2", "Evenementenbeveiliger"],
    contractHoursPerWeek: 32,
    caoMaxHoursPerWeek: 48,
    hireDate: "2022-11-08",
    rating: 4.4,
    avatarColor: AVATAR_COLORS[5],
  },
  {
    id: "emp-7",
    firstName: "Marek",
    lastName: "Kowalski",
    initials: initials("Marek", "Kowalski"),
    email: "marek.kowalski@werkkompas.nl",
    phone: "+31 6 1234 5607",
    city: "Den Haag",
    status: "actief",
    certifications: ["Beveiliger 2", "Hondengeleider", "BHV"],
    contractHoursPerWeek: 40,
    caoMaxHoursPerWeek: 48,
    hireDate: "2021-02-22",
    rating: 4.6,
    avatarColor: AVATAR_COLORS[6],
  },
  {
    id: "emp-8",
    firstName: "Anouk",
    lastName: "de Boer",
    initials: initials("Anouk", "de Boer"),
    email: "anouk.deboer@werkkompas.nl",
    phone: "+31 6 1234 5608",
    city: "Amsterdam",
    status: "actief",
    certifications: ["Beveiliger 2", "Centralist", "EHBO"],
    contractHoursPerWeek: 36,
    caoMaxHoursPerWeek: 48,
    hireDate: "2023-08-14",
    rating: 4.7,
    avatarColor: AVATAR_COLORS[7],
  },
  {
    id: "emp-9",
    firstName: "Bram",
    lastName: "Visser",
    initials: initials("Bram", "Visser"),
    email: "bram.visser@werkkompas.nl",
    phone: "+31 6 1234 5609",
    city: "Rotterdam",
    status: "actief",
    certifications: ["Beveiliger 2", "Horeca Portier"],
    contractHoursPerWeek: 24,
    caoMaxHoursPerWeek: 48,
    hireDate: "2024-01-09",
    rating: 4.3,
    avatarColor: AVATAR_COLORS[0],
  },
  {
    id: "emp-10",
    firstName: "Saskia",
    lastName: "Smit",
    initials: initials("Saskia", "Smit"),
    email: "saskia.smit@werkkompas.nl",
    phone: "+31 6 1234 5610",
    city: "Utrecht",
    status: "actief",
    certifications: ["Beveiliger 2", "Evenementenbeveiliger", "BHV", "EHBO"],
    contractHoursPerWeek: 40,
    caoMaxHoursPerWeek: 48,
    hireDate: "2020-10-11",
    rating: 4.8,
    avatarColor: AVATAR_COLORS[1],
  },
  {
    id: "emp-11",
    firstName: "Karim",
    lastName: "Benali",
    initials: initials("Karim", "Benali"),
    email: "karim.benali@werkkompas.nl",
    phone: "+31 6 1234 5611",
    city: "Den Haag",
    status: "actief",
    certifications: ["Beveiliger 2", "Persoonsbeveiliger", "BHV"],
    contractHoursPerWeek: 40,
    caoMaxHoursPerWeek: 48,
    hireDate: "2021-05-30",
    rating: 4.6,
    avatarColor: AVATAR_COLORS[2],
  },
  {
    id: "emp-12",
    firstName: "Iris",
    lastName: "Hoekstra",
    initials: initials("Iris", "Hoekstra"),
    email: "iris.hoekstra@werkkompas.nl",
    phone: "+31 6 1234 5612",
    city: "Amsterdam",
    status: "actief",
    certifications: ["Beveiliger 2", "Centralist"],
    contractHoursPerWeek: 28,
    caoMaxHoursPerWeek: 48,
    hireDate: "2023-11-27",
    rating: 4.5,
    avatarColor: AVATAR_COLORS[3],
  },
];

// "Today" for the demo. Frozen so the planner shows consistent data.
// Use a fixed reference date so demo always looks consistent regardless of real today.
const REFERENCE = new Date("2026-06-15T08:00:00"); // Monday

const dayOffset = (days: number, hours = 0, minutes = 0) => {
  const d = new Date(REFERENCE);
  d.setDate(d.getDate() + days);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
};

export const REFERENCE_TODAY = REFERENCE.toISOString();

export const MISSIONS: Mission[] = [
  {
    id: "mis-1",
    title: "Toegangscontrole hoofdkantoor",
    client: "ABN AMRO",
    type: "Object",
    location: "Hoofdkantoor Zuidas",
    address: "Gustav Mahlerlaan 10",
    city: "Amsterdam",
    startISO: dayOffset(0, 7, 0),
    endISO: dayOffset(0, 19, 0),
    hourlyRate: 22.5,
    requiredCertifications: ["Beveiliger 2", "BHV"],
    headcount: 2,
    description:
      "Toegangscontrole bij de hoofdingang. Bezoekersregistratie en badge-uitgifte.",
    instructions:
      "Uniform verplicht. Meld je 15 min voor aanvang bij receptie. Pauzes in overleg met collega.",
    invitedEmployeeIds: ["emp-1", "emp-3"],
    assignments: [
      { employeeId: "emp-3", status: "geaccepteerd", respondedAt: dayOffset(-1, 18, 0) },
    ],
    status: "uitgenodigd",
    createdAt: dayOffset(-3, 9, 0),
  },
  {
    id: "mis-2",
    title: "Evenementbeveiliging festival",
    client: "Mojo Concerts",
    type: "Evenement",
    location: "Ziggo Dome - Zomerfestival",
    address: "De Passage 100",
    city: "Amsterdam",
    startISO: dayOffset(2, 16, 0),
    endISO: dayOffset(3, 2, 0),
    hourlyRate: 26.0,
    requiredCertifications: ["Beveiliger 2", "Evenementenbeveiliger"],
    headcount: 6,
    description:
      "Crowd-control en toegangscontrole bij hoofdpodium en VIP-ingang.",
    instructions:
      "Earpiece en gele hesjes worden uitgereikt. Briefing om 15:30 bij ingang 4.",
    invitedEmployeeIds: ["emp-1", "emp-2", "emp-4", "emp-6", "emp-10", "emp-11"],
    assignments: [
      { employeeId: "emp-2", status: "geaccepteerd", respondedAt: dayOffset(-1, 11, 0) },
      { employeeId: "emp-10", status: "geaccepteerd", respondedAt: dayOffset(-1, 14, 0) },
    ],
    status: "uitgenodigd",
    createdAt: dayOffset(-2, 10, 0),
  },
  {
    id: "mis-3",
    title: "Winkelsurveillance",
    client: "Albert Heijn XL",
    type: "Winkel",
    location: "AH XL Beverwaard",
    address: "Oude Watering 175",
    city: "Rotterdam",
    startISO: dayOffset(1, 10, 0),
    endISO: dayOffset(1, 18, 0),
    hourlyRate: 19.5,
    requiredCertifications: ["Beveiliger 2"],
    headcount: 1,
    description:
      "Preventieve surveillance en hulp bij winkeldiefstal in burger.",
    instructions:
      "Burgerkleding. Meld je bij assistent-bedrijfsleider voor briefing.",
    invitedEmployeeIds: ["emp-1", "emp-5", "emp-9"],
    assignments: [],
    status: "open",
    createdAt: dayOffset(-1, 9, 0),
  },
  {
    id: "mis-4",
    title: "Mobiele surveillance bedrijventerrein",
    client: "Park Schieveen Beheer",
    type: "Mobiele surveillance",
    location: "Bedrijventerrein Schieveen",
    address: "Schieveensedijk 41",
    city: "Rotterdam",
    startISO: dayOffset(3, 22, 0),
    endISO: dayOffset(4, 6, 0),
    hourlyRate: 24.0,
    requiredCertifications: ["Beveiliger 2", "Hondengeleider"],
    headcount: 1,
    description:
      "Surveillance per voertuig met hond. Patrouilleer 4 rondes per nacht.",
    instructions: "Voertuig wordt opgehaald bij depot. K9-protocol volgen.",
    invitedEmployeeIds: ["emp-7"],
    assignments: [],
    status: "uitgenodigd",
    createdAt: dayOffset(-1, 14, 0),
  },
  {
    id: "mis-5",
    title: "Horeca portier weekenddienst",
    client: "Club NL",
    type: "Horeca",
    location: "Club NL",
    address: "Rembrandtplein 17",
    city: "Amsterdam",
    startISO: dayOffset(5, 22, 0),
    endISO: dayOffset(6, 4, 0),
    hourlyRate: 25.0,
    requiredCertifications: ["Beveiliger 2", "Horeca Portier"],
    headcount: 3,
    description: "Portierwerk en toezicht op naleving huisregels.",
    instructions: "Dresscode: zwart pak. ID-controle bij ingang.",
    invitedEmployeeIds: ["emp-3", "emp-9", "emp-5"],
    assignments: [
      { employeeId: "emp-3", status: "geaccepteerd", respondedAt: dayOffset(0, 9, 0) },
    ],
    status: "uitgenodigd",
    createdAt: dayOffset(-1, 9, 0),
  },
  {
    id: "mis-6",
    title: "Persoonsbeveiliging diplomatiek bezoek",
    client: "Externe partner",
    type: "Persoonsbeveiliging",
    location: "Hotel Des Indes",
    address: "Lange Voorhout 54-56",
    city: "Den Haag",
    startISO: dayOffset(4, 9, 0),
    endISO: dayOffset(4, 21, 0),
    hourlyRate: 38.0,
    requiredCertifications: ["Beveiliger 2", "Persoonsbeveiliger"],
    headcount: 2,
    description: "PB-team voor een internationale gast.",
    instructions: "Briefing 1u voor aanvang. Discretie vereist.",
    invitedEmployeeIds: ["emp-5", "emp-11"],
    assignments: [
      { employeeId: "emp-11", status: "geaccepteerd", respondedAt: dayOffset(-2, 16, 0) },
    ],
    status: "uitgenodigd",
    createdAt: dayOffset(-4, 11, 0),
  },
  {
    id: "mis-7",
    title: "Centralist nachtdienst",
    client: "Interne meldkamer",
    type: "Object",
    location: "Meldkamer Werkkompas",
    address: "Schiekade 800",
    city: "Rotterdam",
    startISO: dayOffset(0, 22, 0),
    endISO: dayOffset(1, 6, 0),
    hourlyRate: 21.0,
    requiredCertifications: ["Centralist"],
    headcount: 1,
    description: "Bediening alarmsysteem en aansturing mobiele eenheden.",
    instructions: "Overdracht 21:45 met collega. Logboek bijhouden.",
    invitedEmployeeIds: ["emp-2", "emp-8", "emp-12"],
    assignments: [
      { employeeId: "emp-8", status: "geaccepteerd", respondedAt: dayOffset(-1, 13, 0) },
    ],
    status: "uitgenodigd",
    createdAt: dayOffset(-2, 8, 0),
  },
  {
    id: "mis-8",
    title: "Receptie & toegangscontrole",
    client: "Achmea",
    type: "Object",
    location: "Achmea Hoofdkantoor",
    address: "Handelsweg 2",
    city: "Zeist",
    startISO: dayOffset(1, 8, 0),
    endISO: dayOffset(1, 17, 0),
    hourlyRate: 21.5,
    requiredCertifications: ["Beveiliger 2"],
    headcount: 1,
    description: "Receptie ondersteuning, badge-controle.",
    instructions: "Net uniform. Geen telefoon zichtbaar bij balie.",
    invitedEmployeeIds: ["emp-4", "emp-10"],
    assignments: [],
    status: "open",
    createdAt: dayOffset(-1, 10, 0),
  },
  {
    id: "mis-9",
    title: "Evenement - voetbalwedstrijd",
    client: "Feyenoord",
    type: "Evenement",
    location: "Stadion De Kuip",
    address: "Van Zandvlietplein 1",
    city: "Rotterdam",
    startISO: dayOffset(6, 14, 0),
    endISO: dayOffset(6, 23, 0),
    hourlyRate: 23.0,
    requiredCertifications: ["Beveiliger 2", "Evenementenbeveiliger"],
    headcount: 8,
    description: "Stewarding bij thuiswedstrijd, secties Noord en Oost.",
    instructions:
      "Verzamelen poort 6 om 12:30. Hesjes en walkietalkies bij briefing.",
    invitedEmployeeIds: ["emp-1", "emp-2", "emp-4", "emp-5", "emp-6", "emp-9", "emp-10", "emp-11"],
    assignments: [
      { employeeId: "emp-5", status: "geaccepteerd", respondedAt: dayOffset(0, 8, 0) },
    ],
    status: "uitgenodigd",
    createdAt: dayOffset(-2, 12, 0),
  },
  {
    id: "mis-10",
    title: "Beveiliging bouwplaats avond",
    client: "BAM Bouw",
    type: "Object",
    location: "Bouwplaats Merwedekanaalzone",
    address: "Wilhelminakade 92",
    city: "Utrecht",
    startISO: dayOffset(2, 18, 0),
    endISO: dayOffset(3, 2, 0),
    hourlyRate: 22.0,
    requiredCertifications: ["Beveiliger 2"],
    headcount: 1,
    description: "Object- en terreinbeveiliging na werkuren.",
    instructions:
      "Sleutels en sleutelplattegrond bij ingang. Rondes elk uur, logboek.",
    invitedEmployeeIds: ["emp-4", "emp-10", "emp-12"],
    assignments: [],
    status: "open",
    createdAt: dayOffset(0, 7, 30),
  },
];

// Pre-fill some availability around the reference week. State per date.
const startOfWeek = (() => {
  const d = new Date(REFERENCE);
  const dow = (d.getDay() + 6) % 7; // monday = 0
  d.setDate(d.getDate() - dow);
  d.setHours(0, 0, 0, 0);
  return d;
})();

const isoDate = (d: Date) => d.toISOString().slice(0, 10);

const makeWeekAvailability = (
  states: ("beschikbaar" | "voorkeur" | "niet")[],
  weekOffset = 0
) =>
  states.map((state, i) => {
    const d = new Date(startOfWeek);
    d.setDate(d.getDate() + i + weekOffset * 7);
    return { date: isoDate(d), state };
  });

export const AVAILABILITY: EmployeeAvailability[] = [
  {
    employeeId: "emp-1",
    entries: [
      ...makeWeekAvailability(["beschikbaar", "beschikbaar", "voorkeur", "beschikbaar", "niet", "beschikbaar", "beschikbaar"]),
      ...makeWeekAvailability(["beschikbaar", "beschikbaar", "beschikbaar", "voorkeur", "voorkeur", "niet", "niet"], 1),
    ],
  },
  {
    employeeId: "emp-2",
    entries: [
      ...makeWeekAvailability(["beschikbaar", "voorkeur", "beschikbaar", "beschikbaar", "beschikbaar", "voorkeur", "voorkeur"]),
      ...makeWeekAvailability(["voorkeur", "voorkeur", "beschikbaar", "beschikbaar", "niet", "beschikbaar", "beschikbaar"], 1),
    ],
  },
  {
    employeeId: "emp-3",
    entries: [
      ...makeWeekAvailability(["beschikbaar", "beschikbaar", "voorkeur", "beschikbaar", "beschikbaar", "beschikbaar", "niet"]),
    ],
  },
  {
    employeeId: "emp-4",
    entries: [
      ...makeWeekAvailability(["niet", "beschikbaar", "beschikbaar", "voorkeur", "voorkeur", "beschikbaar", "beschikbaar"]),
    ],
  },
  {
    employeeId: "emp-5",
    entries: [
      ...makeWeekAvailability(["beschikbaar", "beschikbaar", "voorkeur", "voorkeur", "beschikbaar", "beschikbaar", "beschikbaar"]),
    ],
  },
];

export const MESSAGE_THREADS: MessageThread[] = [
  {
    id: "thr-1",
    employeeId: "emp-1",
    unread: 1,
    messages: [
      {
        id: "msg-1",
        threadId: "thr-1",
        fromRole: "admin",
        text: "Hoi Sander, kun je woensdagavond invallen voor de bouwplaats?",
        sentAt: dayOffset(-1, 14, 5),
        read: true,
      },
      {
        id: "msg-2",
        threadId: "thr-1",
        fromRole: "employee",
        text: "Zou kunnen, ik laat het je vanavond weten.",
        sentAt: dayOffset(-1, 15, 30),
        read: true,
      },
      {
        id: "msg-3",
        threadId: "thr-1",
        fromRole: "admin",
        text: "Top, ik heb je alvast uitgenodigd voor de dienst.",
        sentAt: dayOffset(0, 9, 12),
        read: false,
      },
    ],
  },
  {
    id: "thr-2",
    employeeId: "emp-2",
    unread: 0,
    messages: [
      {
        id: "msg-4",
        threadId: "thr-2",
        fromRole: "employee",
        text: "De briefing van Mojo, op welke ingang verzamelen we?",
        sentAt: dayOffset(0, 8, 12),
        read: true,
      },
      {
        id: "msg-5",
        threadId: "thr-2",
        fromRole: "admin",
        text: "Poort 4, 15:30. Earpiece krijg je bij de tafel.",
        sentAt: dayOffset(0, 8, 25),
        read: true,
      },
    ],
  },
  {
    id: "thr-3",
    employeeId: "emp-5",
    unread: 2,
    messages: [
      {
        id: "msg-6",
        threadId: "thr-3",
        fromRole: "admin",
        text: "Youssef, beschikbaar voor PB-dienst donderdag?",
        sentAt: dayOffset(-2, 11, 0),
        read: false,
      },
      {
        id: "msg-7",
        threadId: "thr-3",
        fromRole: "admin",
        text: "Briefing 08:00 op locatie.",
        sentAt: dayOffset(-2, 11, 1),
        read: false,
      },
    ],
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif-1",
    kind: "nieuwe-opdracht",
    title: "Nieuwe opdracht beschikbaar",
    body: "Evenementbeveiliging festival - 6 plekken open",
    createdAt: dayOffset(-2, 10, 0),
    read: false,
    forEmployeeId: "emp-1",
    missionId: "mis-2",
  },
  {
    id: "notif-2",
    kind: "bericht",
    title: "Bericht van planning",
    body: "Top, ik heb je alvast uitgenodigd voor de dienst.",
    createdAt: dayOffset(0, 9, 12),
    read: false,
    forEmployeeId: "emp-1",
  },
  {
    id: "notif-3",
    kind: "geaccepteerd",
    title: "Sander accepteerde Toegangscontrole hoofdkantoor",
    body: "ABN AMRO - 15 juni",
    createdAt: dayOffset(-1, 18, 0),
    read: true,
    missionId: "mis-1",
  },
  {
    id: "notif-4",
    kind: "nieuwe-opdracht",
    title: "Open dienst zonder bemensing",
    body: "Beveiliging bouwplaats avond - BAM Bouw",
    createdAt: dayOffset(0, 7, 30),
    read: false,
    missionId: "mis-10",
  },
];
